# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robin Onsay
email: onsayrobin@gmail.com
description: "Robin is a Michigan State University graduate with a Bachelor's degree in Computer Engineering. Their primary areas of interest are in Spacecraft Software Engineering, Wireless and Communication Systems, Embedded Systems, RF circuit design, and Artificial Intelligence. Robin is particularly interested in exercising the skills they have acquired over years of study at MSU and Pathways internships with NASA Johnson Space Center within the context of human spaceflight."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robinonsay.me" # the base hostname & protocol for your site
twitter_username: robinonsay
github_username:  robinonsay
linkedin_username: robinonsay

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
