# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robin Onsay
email: onsayrobin@gmail.com
description: This is the portfolio website and blog for the developer Robin Onsay. This paticular website was built using HTML, CSS, JavaScript, JQuery, and Jekyll. It is being hosted on github as a public repository.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://robinonsay.me" # the base hostname & protocol for your site
twitter_username: OnsayRao
github_username:  robinonsay
linkedin_username: robinonsay

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
